version: '3'

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env

volumes:
  db: